channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - sphinx=5.3.0 # https://github.com/conda-forge/sphinx-feedstock

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==17.4.0 # https://rpaframework.org/releasenotes.html
      - robotframework-docgen==0.15.0 # https://github.com/robocorp/robotframework-docgen
      - robotframeworklexer==1.1 # https://github.com/robotframework/pygmentslexer
